### ISSUE TITLE
A question about installing the R package

### ISSUE THREAD

**Issue by 002-two** [lfpaulin/SVhound#1]
Hello,
I successfully ran the Python script, but failed to install the R package(SVhound)
![image](https://user-images.githubusercontent.com/77915435/170449021-57bb33f7-0a34-47d6-a855-4900104e81fe.png)
I tried versions 4.03 and 4.2 and they didn't work.
I want to known how to solve it.

**Comment by lfpaulin** [comment]
Hello,
SVhound is not yet available directly from the R package repository, in order to install it, please download the code from the github repository as a ZIP file and unpack it.
Then in a terminal, in the same directory where the unpack zip is open an R session and type `install.packages("SVhound-master", repos = NULL, type="source")`
IN the following weeks I will try to place SVhound in the R package repository
